### PR TITLE
Feature/dl full timeseries

### LINKED ISSUE #28: Add option to web UI to download full time range
As noted in #27, 85% of our raster downloads are for the full timeseries `min_date` to `max_date`. We should add a control to the UI  to make that use case simpler. That could be one of the following:
- add a disable checkbox to the calendar selector to use the full range
- add a hyperlink to the "Download" fieldset that says "Download all" or "Download full time range" or something.

### PR DESCRIPTION
**Pull request by CBMasri**
Fixes #28

### CODE REVIEW

**Comment by jameshiebert** [comment]
Do you have a demo deployed on docker yet?

**Comment by CBMasri** [comment]
Yep, there should be one available [here](http://docker2.pcic.uvic.ca:8081/downscaled_gcms/map/).

**Comment by CBMasri** [comment]
I'm going to close this PR and open a new one that has only the relevant commits, the rebase should have been a merge.

**Comment by jameshiebert** [comment]
Perfect, thanks! I was wondering about that.

**Pull request closed without merging**
