### PR TITLE
Jenkins Pipeline Update

### PR DESCRIPTION
**Pull request by nikola-rados**
This update applies the new features found in the [`climate-explorer-frontend Jenkinsfile`](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/Jenkinsfile).

Features added:
- tag tracking
- reduced usage of security scan
- more consistent image naming

These features are found in two other projects and will eventually be factored out.

### CODE REVIEW

**Comment by nikola-rados** [comment]
The functionality added was to collect and process the git tags.  These changes do not just apply to `master`.  If the branch is `master` and is tagged on git, we want to push the git tag(s) along with the `latest` tag to docker hub.  If the branch is not `master` we use the branch name as the tag.

**Comment by nikola-rados** [comment]
Rather than open _another_ PR for _another_ `Jenkinsfile` update, I thought I would extend this one.  The changes in the most recent commit maintain the same functionality added by this PR, but do so using the shared library.

**Comment by nikola-rados** [comment]
@corviday that was not intended.  Did you produce that image?

**Comment by nikola-rados** [comment]
I re-ran the pipeline (with a small change that wasn't relevant to image naming) and it produced the expected output.  Would you be able to tell me how you produced the result you got?

**Comment by corviday** [comment]
Hm, I might have branched off the wrong place for my tests. I'll try again.

**Pull request merged**
